#!/bin/sh
#
# /etc/init.d/tomcat6 -- startup script for the Tomcat 6 servlet engine
#
# Written by Cleiton Bueno <cleiton.bueno@b2open.com>
#
### BEGIN INIT INFO
# Provides:          tomcat6
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=tomcat6
DESC="Tomcat6 servlet2.5"
DEFAULT=/etc/default/$NAME


if [ `id -u` -ne 0 ]; then
  echo "You need root privileges to run this script"
  exit 1
fi


if [ -r /etc/default/rcS ]; then
  . /etc/default/rcS
fi


# Check Java exist, based entry in /etc/profile
JAVA_HOME=""
for dir in /usr/lib/jvm/*; do
  if [ -x "${dir}/bin/java" ]; then
    [ -z "${JAVA_HOME}"] && JAVA_HOME="${dir}"
  fi
done

if [ -n "${JAVA_HOME}" ]; then
  export JAVA_HOME=${JAVA_HOME}
else
  echo "[$NAME] Java JVM not found!"
  exit 3
fi


# Create directory /var/log/tomcat6 - WORKAROUND /var is volatile
mkdir -p /var/log/tomcat6

# Directory where the Tomcat 6 binaries
export CATALINA_HOME=/usr/share/$NAME
export CATALINA_BASE=/usr/share/$NAME

# Script Start Tomcat6
START_TOMCAT=$CATALINA_HOME/bin/startup.sh

# Script Stop Tomcat6
STOP_TOMCAT=$CATALINA_HOME/bin/shutdown.sh

# Define variable to PID Tomcat6
CATALINA_PID="/var/run/$NAME.pid"


case "$1" in
  start)
    echo "Starting $DESC" "$NAME"
    $START_TOMCAT
    ;;
  stop)
    echo "Stopping $DESC" "$NAME"
    $STOP_TOMCAT
    rm -f "$CATALINA_PID"
    ;;
  status)
    if [ -f "$CATALINA_PID" ]; then
      echo "$DESC is not running, but pid file exists."
      exit 1
    else
      echo "$DESC is not running."
      exit 3
    fi
    ;;
  restart|force-reload)
    if [ -f "$CATALINA_PID" ]; then
      $0 stop
      sleep 1
    fi
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
